"""
Django settings for IC_django project.
Generated by 'django-admin startproject' using Django 5.0.6 Edited by Shivam.
"""
from pathlib import Path
from logger import logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
logging.info(f"Base directory: {BASE_DIR}")  #

# Media URL
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'IC_django' / 'media'
logging.info(f"Media URL {MEDIA_URL}, root: {MEDIA_ROOT}")


STATIC_URL = '/static/'
# Optionally, you can define STATIC_ROOT if you plan to use the collectstatic command
STATIC_ROOT = BASE_DIR / 'IC_django' / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'IC_django' / 'static',
]
logging.info(f"Static_url {STATIC_URL} staic_dir {STATICFILES_DIRS}")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v5e9#z8b3d(e3xt9xm!+0xmizzvkbo2*z&j^t^1e&+#rf^%#(y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes', 
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'IC_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'IC_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'IC_django' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'IC_django.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'